config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/profile/:id', to: 'users#show', as: 'profile'

  resources :posts, except: :destroy do
    member do
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:create, :new, :show]
  resources :users, except: [:show, :destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true

  def to_param
    self.slug
  end

  def generate_slug
    self.slug = "#{self.id}-#{self.name.parameterize}"
    self
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post


  validates :body, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true
  validates :url, presence: true, uniqueness: { case_sensitive: false }

  def to_param
    self.slug
  end

  def generate_slug
    self.slug = "#{self.id}-#{self.title.parameterize}"
    self
  end

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, on: :create, length: { minimum: 6 }
  validates_length_of :password, minimum: 6, on: :update, allow_blank: true

  before_save :generate_slug

  def to_param
    self.slug
  end

  def generate_slug
    self.slug = self.username.parameterize
  end

  def admin?
    self.role == 'admin'
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :votable, polymorphic: true

  validates_uniqueness_of :creator, scope: [:votable_type, :votable_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_categories
  before_filter :current_user
  helper_method :current_user, :logged_in?

  def set_categories
    @categories = Category.all
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "Must be logged in to do that."
      redirect_to login_path
    end
  end

  def require_admin
    access_denied unless logged_in? and current_user.admin?
  end

  def access_denied
    flash[:error] = "Access denied."
    redirect_to root_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, except: :show
  before_action :require_admin, except: :show

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      @category.generate_slug.save
      flash[:notice] = "New category was created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comments_param)
    @comment.creator = @current_user
    if @comment.save
      flash[:notice] = "You comment is saved."
      redirect_to post_path(@post)
    else
      @post.comments.reload
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    vote = Vote.create(vote: params[:vote], creator: current_user, votable: @comment)
    @vote_valid = vote.valid?
    @success_msg = "Your vote is counted."
    @error_msg = "Your can only vote for this comment once."
    respond_to do |format|
      format.html {
        if @vote.valid
          flash[:notice] = @success_msg
        else
          flash[:error] = @error_msg
        end
        redirect_to :back
      }

      format.js {
        @obj = @comment
        render 'shared/vote'
      }
    end
  end

  private

  def comments_param
    params.require(:comment).permit(:body, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]

  def index
    @posts = Post.all
    respond_to do |format|
      format.html
      format.any(:xml, :json) { render request.format.to_sym => @posts }
    end
  end

  def show
    @comment = Comment.new
    respond_to do |format|
      format.html
      format.any(:xml, :json) { render request.format.to_sym => @post }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = @current_user
    if @post.save
      @post.generate_slug.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @post.update(post_params)
      @post.generate_slug.save
      flash[:notice] = "Your post was modified."
      redirect_to posts_path
    else
      render :edit
    end
  end

  def vote
    vote = Vote.create(vote: params[:vote], creator: current_user, votable: @post)
    @vote_valid = vote.valid?
    @success_msg = "Your vote is counted."
    @error_msg = "You can only vote for this post once."
    respond_to do |format|
      format.html {
        if @vote_valid
          flash[:notice] = @success_msg
        else
          flash[:error] = @error_msg
        end
        redirect_to :back
      }

      format.js {
        @obj = @post
        render 'shared/vote'
      }
    end
  end

  ### TO-DO: getter for post.creator.username


  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.where('lower(username) = ?', params[:user][:username].downcase).first
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash[:error] = "There's something wrong with your username/password. Please try again."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out successfully. Bye!"
    redirect_to posts_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, except: [:new, :create]

  def index

  end

  def show
    @user = User.find_by(slug: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Your account has been created. Welcome aboard!"
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "Your profile has been updated."
      redirect_to profile_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,:password,:time_zone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url (url)
    url.starts_with?('http://') ? url : "http://#{url}"
  end

  def display_datetime(dt)
    dt = dt.in_time_zone(current_user.time_zone) if logged_in? and current_user.time_zone
    dt.strftime("%m/%d/%Y %l:%M %p %Z")
  end

  def count_votes(arr)
    up_vote = arr.select {|v| v.vote }
    down_vote = arr.select {|v| !v.vote }
    up_vote.size - down_vote.size
  end

end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"label label-category" %>

app/views/categories/_form.html.erb
<%= render 'shared/form_error', object: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit "Save", class: "btn" %>
<% end %>

app/views/categories/new.html.erb
<%= render 'shared/form_block', title: "Create new category" %>

app/views/categories/show.html.erb
<ul class="breadcrumb">
  <li>
    <%= link_to "All posts", posts_path %>
    <span class="divider">&gt;</span>
  </li>
  <li class="active"><%= render @category %></li>
</ul>

<% @category.posts.each do |post| %>
  <%= render 'posts/post_block', post: post %>
<% end %>

app/views/comments/_comment.html.erb
<div class="row">
  <div class="well span1 text-center">
    <%= render 'shared/vote_block',
          link_up: vote_post_comment_path(comment.post, comment, vote: true),
          link_down: vote_post_comment_path(comment.post, comment, vote: false),
          obj: comment  %>
  </div>
  <div class="well span7">
    <div>
      <b><%= comment.creator.username %> </b>
      "<%= comment.body %>"
      <% if show_post_title %>
        on <%= link_to comment.post.title, post_path(comment.post) %>
      <% end %>
    </div>
    <em><%= time_ago_in_words(comment.updated_at) %> ago</em>
    <small class="muted">(<%= display_datetime(comment.updated_at) %>)</small>
  </div>
</div>

app/views/comments/_form.html.erb
<%= render 'shared/form_error', object: @comment %>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :body, "Leave a comment" %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/comments/vote.js.erb
<% if @vote_valid %>
  $('#comment_<%= @comment.id %>_votes').html('<%= pluralize(count_votes(@comment.votes), 'vote') %>');
  PostIt.showModal('Success','<%= @success_msg %>');
<% else %>
  PostIt.showModal('Error','<%= @error_msg %>');
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to "All posts", posts_path %>
  </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <% @categories.each do |c| %>
        <li><%= link_to c.name, category_path(c)%></li>
      <% end %>
      <% if logged_in? and current_user.admin? %>
        <li class="divider"></li>
        <li>
          <%= link_to new_category_path do %>
            + Create a category
          <% end %>
        </li>
      <% end %>
    </ul>
  </li>
  <% if logged_in? %>
    <li>
      <%= link_to "+ Create a post", new_post_path %>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="icon-user icon-white"> </i> <%= current_user.username %>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to profile_path(current_user) do %>
            View Profile
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_path(current_user) do %>
            Edit Profile
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to "Log out", logout_path %>
        </li>
      </ul>
    </li>

  <% else %>
    <li>
      <%= link_to "Log in", login_path %>
    </li>
    <li>
      <%= link_to "Register", new_user_path %>
    </li>
  <% end %>


</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar navbar-inverse">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
      </div> <!--! end of #main -->
      <div id="modal-box" class="modal hide fade">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 id="modal-box-title"></h4>
        </div>
        <div class="modal-body">
          <div id="modal-box-body"></div>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn" data-dismiss="modal">Close</a>
        </div>
      </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/form_error', object: @post %>

<%= form_for @post do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br />
  <%= f.collection_check_boxes(:category_ids, @categories, :id, :name) do |b| %>
    <%= b.label(class: 'inline checkbox') { b.check_box + b.text} %>
  <% end %>
  <hr />
  <%= f.submit "Save", class: "btn btn-primary" %>

<% end %>

app/views/posts/_post.html.erb
<h4>
  <b><%= link_to post.title, post_path(post) %></b>
</h4>
<%= link_to fix_url(post.url), fix_url(post.url) %><br>
<%= post.description %><br>
<div>
  -- by <%= link_to post.creator.username, profile_path(post.creator) %>
  <em><%= time_ago_in_words(post.updated_at) %> ago</em>
  <small class="muted">(<%= display_datetime(post.updated_at) %>)</small>
</div>

app/views/posts/_post_block.html.erb
<div class="row">
  <div class="well span1 text-center">
    <%= render 'shared/vote_block',
          link_up: vote_post_path(post, vote: true),
          link_down: vote_post_path(post, vote: false),
          obj: post %>

  </div>

  <div class="well span6">
    <div><%= render post.categories %></div>
    <% if logged_in? && post.creator == current_user %>
      <%= link_to "edit", edit_post_path(post), class: "btn btn-mini pull-right" %>
    <% end %>
    <%= render post %>

    <div class="pull-right">
      <%= link_to pluralize(post.comments.size, 'comment'), post_path(post) %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/form_block', title: "Edit a post" %>

app/views/posts/index.html.erb
<ul class="breadcrumb">
  <li class="active">All posts</li>
</ul>

<% @posts.each do |post| %>
 <%= render 'post_block', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/form_block', title: "Create a post" %>

app/views/posts/show.html.erb
<div class="hero-unit">
  <div class="pull-right">
    <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-small" if logged_in? %>
  </div>
  <%= render @post %>
  <%= render @post.categories %>
</div>
<hr />

<h4>Comments</h4>
<%= render "comments/form" if logged_in? %>

<div class="container-fluid">
  <%= render @post.comments, show_post_title: false%>
</div>

app/views/shared/_form_block.html.erb
<div class="well">
  <h4><%= title %></h4>
  <%= render 'form' %>
</div>

app/views/shared/_form_error.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_vote_block.html.erb
<% if logged_in? %>
  <div>
    <%= link_to link_up, method: 'post', remote: true, class: 'btn btn-mini' do %>
      <i class="icon-chevron-up"></i>
    <% end %>
  </div>
<% end %>
<div id="<%= "#{obj.class}_#{obj.id}_votes" %>">
  <%= pluralize(count_votes(obj.votes), 'vote') %>
</div>

<% if logged_in? %>
  <div>
    <%= link_to link_down, method: 'post', remote: true, class: 'btn btn-mini' do %>
      <i class="icon-chevron-down"></i>
    <% end %>
  </div>
<% end %>

app/views/shared/vote.js.erb
<% if @vote_valid %>
  $('#<%= @obj.class %>_<%= @obj.id %>_votes').html('<%= pluralize(count_votes(@obj.votes), 'vote') %>');
  PostIt.showModal('Success','<%= @success_msg %>');
<% else %>
  PostIt.showModal('Error','<%= @error_msg %>');
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/form_error', object: @user %>

<%= form_for @user do |f| %>
  <%= f.label :username%>
  <%= f.text_field :username %>
  <%= f.label :password, ['edit','update'].include?(params[:action]) ? 'Change password' : 'Password' %>
  <%= f.password_field :password %>
  <%= f.label :time_zone %>
  <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: 'Pacific Time (US & Canada)', include_blank: true %>
  <br />
  <%= f.submit "Submit", class:"btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/form_block', title: "Edit profile" %>

app/views/users/index.html.erb
show all users

app/views/users/new.html.erb
<%= render 'shared/form_block', title: "Register" %>

app/views/users/show.html.erb
<h4>User Profile</h4>
<table>
  <tr>
    <th align="right">Username: </th>
    <td><%= @user.username %></td>
  </tr>
  <tr>
    <th align="right">Time Zone: </th>
    <td><%= @user.time_zone %></td>
  </tr>
</table>

<hr />

<ul id="profile-tab" class="nav nav-tabs">
  <li class="active">
    <a data-toggle="tab" href="#post-content">Posts (<%= @user.posts.size %>)</a>
  </li>
  <li>
    <a data-toggle="tab" href="#comment-content">Comments (<%= @user.comments.size %>)</a>
  </li>
</ul>

<div id="profile-tab-content" class="tab-content">
  <div id="post-content" class="tab-pane in active">
    <% @user.posts.each do |post| %>
      <%= render 'posts/post_block', post: post %>
    <% end %>
  </div>

  <div id="comment-content" class="tab-pane">
    <%= render @user.comments, show_post_title: true%>
  </div>

</div>